---

default:
  image: registry.cri.epita.fr/cri/infrastructure/nixpie/nixos-pie
  before_script:
    - mkdir -p /tmp /var/tmp
    - meson setup -Ddoc=true builddir

stages:
  - build
  - test
  - qa
  - doc

build:
  stage: build
  script:
    - meson compile -C builddir
  artifacts:
    paths:
      - builddir/42sh
    expose_as: 42sh

Geoffroy_test_command:
  stage: test
  script:
    - tests/run_tests_command_exec

Geoffroy_test_echo:
  stage: test
  script:
    - tests/run_tests_echo

Geoffroy_test_redir:
  stage: test
  script:
    - tests/run_tests_redir

Geoffroy_test_pipe:
  stage: test
  script:
    - tests/run_tests_pipe

Anna_test_lexer:
  stage: test
  script:
    - tests/run_tests_2

Anna_test_variables:
  stage: test
  script:
    - tests/tests_variables

Anna_test_for:
  stage: test
  script:
    - tests/run_tests_lexer_for

test:
  stage: test
  dependencies:
    - build
  script:
    - tests/run_tests builddir/42sh

week_1:
  stage: test
  dependencies:
    - build
  script:
    - tests/week1/tests_if_echo builddir/42sh

week_1_echo Geoff:
  stage: test
  dependencies:
    - build
  script:
    - tests/week1/tests_echo builddir/42sh

concat:
  stage: test
  dependencies:
    - build
  script:
    - tests/week1/tests_concat builddir/42sh

week_2_pipe:
  stage: test
  dependencies:
    - build
  script:
    - tests/week2/tests_pipe builddir/42sh

week_3:
  stage: test
  dependencies:
    - build
  script:
    - tests/week3/test_dot builddir/42sh

tests_unset:
  stage: test
  dependencies:
    - build
  script:
    - tests/week3/tests_unset builddir/42sh

error_if:
  stage: test
  dependencies:
    - build
  script:
    - tests/run_test_error_if builddir/42sh

week_2_while:
  stage: test
  dependencies:
    - build
  script:
    - tests/week2/tests_while builddir/42sh

elif_is_a_bitch:
  stage: test
  dependencies:
    - build
  script:
    - tests/week3/test_elif builddir/42sh

clang-format:
  stage: qa
  needs: []
  before_script: []
  script:
    - find . -type f -name '*.[ch]' -exec clang-format --style=file -i {} ';'
    - git diff --exit-code
  after_script:
    - git diff > diff
  artifacts:
    paths:
      - diff
    expose_as: clang-format diff
    when: on_failure

doc:
  stage: doc
  needs: []
  script:
    - meson compile -C builddir doxygen_doc
  artifacts:
    paths:
      - builddir/doxygen_doc
    expose_as: documentation
