#!/bin/bash

echo "*********** Test 1 with if/echo/ \$ **********"
diff <(./builddir/42sh tests/week1/test_var.sh) <(printf "2 b
foo coucou tchoin
")

echo "*********** Test 2 with if/echo/ \$ **********"
diff <(./builddir/42sh tests/week1/test_var2.sh) <(printf "$
")

echo "*********** Test 3 with if/echo/ \$ **********"
diff <(./builddir/42sh tests/week1/test_var3.sh) <(printf "hihi
")