#!/bin/bash

gcc src/lexer/lexer.c src/lexer/token.c src/lexer/token_printer.c src/lexer/for_lexer.c -o token_printer
echo "********* Testing Lexer 1 ***********"
diff <(./token_printer "If echo 'hello my name is ' Anna; then echo bs") <(printf "If
echo
hello my name is 
Anna
;
Then
echo
bs
EOF
")
var1=$?
#rm ./token_printer
if [ $var1 -ne 0 ]; 
then
echo "error"
rm ./token_printer
exit 1;
fi
echo "done [ok] "

echo "********* Testing Lexer 2 ***********"
diff <(./token_printer "if echo b; then echo a; fi") <(printf "If
echo
b
;
Then
echo
a
;
Fi
EOF
")
var2=$?
if [ $var2 -ne 0 ]; 
then
echo "error"
rm ./token_printer
exit 1;
fi
echo "done [ok] "

echo "********* Testing Lexer 3 ***********"
diff <(./token_printer "if echo b; then echo a; fi") <(printf "If
echo
b
;
Then
echo
a
;
Fi
EOF
")
var2=$?
if [ $var2 -ne 0 ]; 
then
rm ./token_printer
exit 1;
fi
echo "done [ok] "
rm ./token_printer