#!/bin/bash

gcc src/lexer/lexer.c src/lexer/token.c src/lexer/token_printer.c -o token_printer
echo "********* Testing Lexer 1 ***********"
./token_printer "If echo 'hello my name is ' Anna; then echo bs"
var1=$?
#rm ./token_printer
if [ $var1 -ne 0 ]; 
then
echo "error"
rm ./token_printer
exit 1;
fi
"done [ok] "

echo "********* Testing Lexer 2 ***********"
diff <(./token_printer "if echo b; then echo a; fi") <(printf "If\necho\nb\n;\nThen\necho\na\n;\nFi\nEOF\n")
var2=$?
if [ $var2 -ne 0 ]; 
then
echo "error"
rm ./token_printer
exit 1;
fi
"done [ok] "

echo "********* Testing Lexer 3 ***********"
./token_printer "if echo b; then echo a; fi"
var2=$?
if [ $var2 -ne 0 ]; 
then
echo "error"
rm ./token_printer
exit 1;
fi
"done [ok] "