#!/bin/bash

echo "*********** Test 1 break for  ***********"
diff <(./builddir/42sh -c "for i in lol do; do if [ 2 -ne 3 ]; then break; fi; echo \$i; done") <(printf "
")
echo "*********** Test 2 continue for  ***********"
diff <(./builddir/42sh -c "for i in lol do; do if [ 2 -ne 3 ]; then echo heya; continue; fi; echo \$i; done") <(printf "heya
heya
")
