#!/bin/bash

echo "*********** Test 1 dot ***********"
diff <(./builddir/42sh -c "./tests/week3/test1.sh") <(printf "c
")

echo "*********** Test 2 dot ***********"
diff <(./builddir/42sh -c ". tests/week3/test2.sh") <(printf "a 
b 
")

if [ ./builddir/42sh -c ". tests/week3/test3.sh" -ne 3 ]; 
then
exit 1;
fi