#!/bin/bash

echo "*********** Test 1 dot ***********"
diff <(./builddir/42sh -c "./test1.sh") <(printf "c
")

echo "*********** Test 2 dot ***********"
diff <(./builddir/42sh -c "./test2.sh") <(printf "a
b
")
